module.exports = {
  BAD_REQUEST: "Some essential data is missing or incorrect",
  SERVER_ERROR: "Internal server error",
  UNAUTHORIZED: "Unauthorized",
  INVALID_EMAIL: "Please provide valid email",
  EMAIL_USED: "email is already in use",
  MOBILE_USED: "Mobile No is already in use",
  INVALID_PASS: "Please provide valid password",
  SESSION_EXIST:
    "Someone is already using this table, but you can view the menu",
  OCCUPIED: "You have already occupied another table, but you can view the menu",
  OCCUPIED_WAIT: "You have already scan waiting QR code, now please scan table QR code",
  CHECKOUTED:
    "You have already checkouted, please complete your payment process",
    
  SESSION_EXIST_REST:
    "You have already join other restaurant, but you can view the menu",
  ALREADY_SCAN_TAKEAWAY: "You cannot access multiple Qrcode at a time",
  PASSWORD_MISMATCH: "You have entered wrong current Password",
  PASSWORD_NOT_EQUAL: "New Password and Re-entered Password does not match",
  SUCCESS_UPDATED: "Successfully updated",
  SUCCESS_ADDED: "Successfully added",
  SUCCESS_REMOVED: "Successfully removed",
  SUCCESS_CHANGED: "Successfully changed",
  REQUEST_SENT_ALLREADAY: "Your request is already sent to the restaurants",
  REQUEST_SENT: "Your request is sent to the restaurant, wait for accept",
  REQUEST_NOT_ACCEPT:
    "Your request is not accepted by restaurant yet, wait for accept",
  REJECT_REQUEST: "Your request is rejected by restaurant",
  BLOCK: "Your are temporary blocked, you will be unlocked within 2 days",
  ACCEPT_REQUEST_ADMIN: "Request is successfully accepted",
  BLOCK_REQUEST_ADMIN: "Customer is successfully blocked",
  REJECT_REQUEST_ADMIN: "Request is successfully rejected by restaurant",
  RESTORED: "Successfully restored",
  NOT_REGISTERED: "Restaurant is not registred yet",
  NOT_VERIFIED: "Your restaurant is not verified yet",
  LOCKED: "Your account has been locked",
  FORBIDDEN_REQ: "Your are not allowed to process this request",
  ALREARY_REGISTRED: "You have already registred restaurant",
  INVOICE_GEN: "Invoice has been geenrated successfully",
  LOCKED_REST: "Restaurant is successfully locked",
  UNLOCKED_REST: "Restaurant is successfully unlocked",
  SCAN_QR: "Scan QR code properly",
  REST_STEP_INCOMPLETE: "Restaurant registration process is incomplete !",
  INVALID_CAPTAIN: "You are not a valid captain for this order",
  INVALID_TABLE: "Inavlid table no",
};
