module.exports = {
  BAD_REQUEST: "Some essential data is missing or incorrect",
  SERVER_ERROR: "Internal server error",
  UNAUTHORIZED: "Unauthorized",
  INVALID_EMAIL: "Please provide valid email",
  EMAIL_USED: "email is already in use",
  MOBILE_USED: "Mobile No is already in use",
  INVALID_PASS: "Please provide valid password",
  SESSION_EXIST: "Someone is already using this table",
  FORBIDDEN: "You have already occupied another table",
  SESSION_EXIST_REST: "You have already join other restaurant",
  PASSWORD_MISMATCH: "You have entered wrong current Password",
  PASSWORD_NOT_EQUAL: "New Password and Re-entered Password does not match",
  SUCCESS_UPDATED: "Successfully updated",
  SUCCESS_ADDED: "Successfully added",
  SUCCESS_REMOVED: "Successfully removed",
  SUCCESS_CHANGED: "Successfully changed",
  REQUEST_SENT_ALLREADAY: "Your request is already sent to the restaurants",
  REQUEST_SENT: "Your request is sent to the restaurant, wait for accept",
  REJECT_REQUEST: "Your request is rejected by restaurant",
  BLOCK: "Your are temporary blocked, you will be unlocked within 2 days",
  ACCEPT_REQUEST_ADMIN: "Request is successfully accepted",
  REJECT_REQUEST_ADMIN: "Request is successfully rejected",
  ALREADY_SCAN_TAKEAWAY: "Scanning another qrcode is prohibitate"
};
