module.exports = {
  BAD_REQUEST: 'Some essential data is missing or incorrect',
  SERVER_ERROR: 'Internal server error',
  UNAUTHORIZED: 'Unauthorized',
  INVALID_EMAIL: 'Please provide valid email',
  EMAIL_USED: 'email is already in use',
  MOBILE_USED: 'Mobile No is already in use',
  INVALID_PASS: 'Please provide valid password',
  SESSION_EXIST: 'Someone is already using this table',
  FORBIDDEN: 'You have already occupied another table',
  SESSION_EXIST_REST: 'You have already join other restaurant',
  PASSWORD_MISMATCH: 'You have entered wrong current Password',
  PASSWORD_NOT_EQUAL: 'New Password and Re-entered Password does not match', 
  SUCCESS_UPDATED: 'Successfully updated',
  SUCCESS_ADDED: 'Successfully added',
  SUCCESS_REMOVED: 'Successfully removed',
  SUCCESS_CHANGED: 'Successfully changed',
};
